name: 'Amazon ECR Login'
description: 'Amazon ECR Login with ncarb default credentials'
inputs: {}
outputs:
  registry:
    description: "ECR Registry"
    value: ${{ steps.amz-login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: 'arn:aws:iam::672033841050:role/github-ecr-push-pull'
        role-duration-seconds: 900
    - name: Login to Amazon ECR
      id: amz-login-ecr
      uses: aws-actions/amazon-ecr-login@v1
