name: 'Amazon ECR Login'
description: 'Amazon ECR Login with ncarb default credentials'
inputs: 
  aws-access-key-id:
    description: >-
      AWS Access Key ID. This input is required if running in the GitHub hosted environment.
      It is optional if running in a self-hosted environment that already has AWS credentials,
      for example on an EC2 instance.
    required: false
  aws-secret-access-key:
    description: >-
      AWS Secret Access Key. This input is required if running in the GitHub hosted environment.
      It is optional if running in a self-hosted environment that already has AWS credentials,
      for example on an EC2 instance.
    required: false
outputs:
  registry:
    description: "ECR Registry"
    value: ${{ steps.amz-login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
        role-to-assume: 'arn:aws:iam::672033841050:role/github-ecr-push-pull'
        role-duration-seconds: 900
    - name: Login to Amazon ECR
      id: amz-login-ecr
      uses: aws-actions/amazon-ecr-login@v1
