name: 'Amazon ECR Login'
description: 'Amazon ECR Login with ncarb default credentials'
inputs:
  aws-region:
    description: 'AWS Region, e.g. us-east-1'
    default: 'us-east-1'
    required: false
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    default: 'arn:aws:iam::672033841050:role/ncarb-github-actions-oidc'
    required: false
  role-duration-seconds:
    description: "Role duration in seconds (default: 15 minutes)"
    required: false
    default: 900
outputs:
  registry:
    description: "ECR Registry"
    value: ${{ steps.amz-login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}
    - name: Login to Amazon ECR
      id: amz-login-ecr
      uses: aws-actions/amazon-ecr-login@v1
